[workspace]
resolver = "2"
members = [
    "libs/zukmove-core",
    "apps/polytech",
    "apps/erasmumu",
    "apps/mi8",
    "apps/colporteur",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["jorisvilardell <joris.vilardell@outlook.com>"]
license = "Apache-2.0"
